### ISSUE TITLE
Uncaught SyntaxError when building in composer.js

### ISSUE THREAD

**Issue by GeoffreyVDB** [thomasjo/atom-latex#136]
Hello, I updated the package yesterday and today I'm getting the following error when trying to build a latex document

**Atom Version**: 1.0.19
**System**: Microsoft Windows 10 Pro
**Thrown From**: [latex](https://github.com/thomasjo/atom-latex) package, v0.28.0

### Stack Trace

Uncaught SyntaxError: C:\Users\user\.atom\packages\latex\lib\composer.js:1
(function (exports, require, module, <b>__filename</b>, __dirname) { 
                                                              
<b>Unexpected token ILLEGAL</b>

```
At C:\Users\user\.atom\packages\latex\lib\composer.js:1

C:\Users\user\.atom\packages\latex\lib\composer.js:1
(function (exports, require, module, __filename, __dirname) { 
                                                              
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:411:25)
    at Object.defineProperty.value [as .js] (C:\Users\user\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.bootstrap (C:/Users/user/.atom/packages/latex/lib/main.js:50:22)
    at atom-workspace.latexBuild (C:/Users/user/.atom/packages/latex/lib/main.js:11:14)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\user\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:245:29)
```

### Commands

```
  2x -2:09.0 latex:build (atom-text-editor.editor.is-focused)
     -0:15 latex:clean (atom-text-editor.editor.is-focused)
     -0:02.3.0 latex:build (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "latex": {
    "sumatraPath": "C:\\Program Files\\SumatraPDF\\SumatraPDF.exe"
  }
}
```

### Installed Packages

```coffee
# User
language-latex, v0.6.1
latex, v0.28.0
latexer, v0.2.7
markdown-preview-plus, v2.2.2

# Dev
No dev packages
```

**Comment by GeoffreyVDB** [comment]
Seems that I'm having disk issues, closed

**Comment by higorn** [comment]
Hi. I'm trying to build my .tex file doing ctrl-alt-b, but it compile a hello2 file instead of my .tex file.
Why it's happening?
