### ISSUE TITLE
Failed to load the latex package

### ISSUE THREAD

**Issue by jhbriese** [thomasjo/atom-latex#145]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [latex](https://github.com/thomasjo/atom-latex) package, v0.28.2

### Stack Trace

Failed to load the latex package

```
At Cannot find module 'lodash'

Error: Cannot find module 'lodash'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (/opt/homebrew-cask/Caskroom/atom/1.0.11/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/Users/jan/.atom/packages/latex/lib/werkzeug.js:8:15)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .js] (/opt/homebrew-cask/Caskroom/atom/1.0.11/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/Users/jan/.atom/packages/latex/lib/config-schema.js:5:17)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .js] (/opt/homebrew-cask/Caskroom/atom/1.0.11/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-js-standard",
      "linter-jsl",
      "linter-jscs",
      "linter-htmlhint"
    ]
  },
  "latex": {}
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.3
editorconfig, v1.2.2
file-icons, v1.6.11
language-latex, v0.6.1
latex, v0.28.2
linter, v1.10.0
linter-chktex, v1.2.3
linter-jsonlint, v1.0.1
linter-php, v1.1.0
linter-sass-lint, v0.4.1
minimap, v4.16.0
project-manager, v2.6.5

# Dev
No dev packages
```

**Comment by m0nhawk** [comment]
Try reinstalling the `latex` package. You are missing node module `lodash`, which is the requierements for `latex` package.

**Comment by thomasjo** [comment]
Easier way to remedy this is to reinstall, but otherwise you can navigate to the package directory and execute `apm install` from there. A typical example would be
```bash
$ cd ~/.atom/packages/latex
$ apm install
```

If you've cloned the repo, as mentioned by @m0nhawk, then you need to run `apm install` from the repo path.

**Comment by thomasjo** [comment]
I'm closing this under the assumption that the problem was resolved. If that is not the case, please re-open and provide more details.
