### ISSUE TITLE
Uncaught TypeError: latex.getBuilder is not a function

### ISSUE THREAD

**Issue by iblacksand** [thomasjo/atom-latex#195]
All I did was go to latex:sync with the pdf on one split and the .tex on the other
**Atom Version**: 1.8.0
**System**: Microsoft Windows 10 Home
**Thrown From**: [latex](https://github.com/thomasjo/atom-latex) package, v0.33.1

### Stack Trace

Uncaught TypeError: latex.getBuilder is not a function

```
At /C:/Users/user/.atom/packages/latex/lib/composer.js:195

TypeError: latex.getBuilder is not a function
    at Composer.resolveOutputFilePath (C:/Users/user/.atom/packages/latex/lib/composer.js:148:29)
    at Composer.sync (C:/Users/user/.atom/packages/latex/lib/composer.js:72:33)
    at atom-workspace.latexSync (C:/Users/user/.atom/packages/latex/lib/main.js:13:41)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\user\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\user\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\user\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\user\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (C:\Users\user\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\user\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\user\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\user\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\user\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\user\AppData\Local\atom\app-1.8.0\resources\app.asar\src\window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (C:\Users\user\AppData\Local\atom\app-1.8.0\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
  2x -0:27.2.0 tabs:split-right (li.tab.sortable.pending-tab.active.right-clicked)
     -0:05.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:03.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:03.2.0 latex:sync (atom-text-editor.editor)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
latex, v0.33.1
pdf-view, v0.50.0

# Dev
No dev packages
```

**Comment by thomasjo** [comment]
Thanks for the report! This should be resolved in v0.34.0 thanks to @yitzchak 🙇
