### ISSUE TITLE
Atom fails to activate the package

### ISSUE THREAD

**Issue by eroniki** [thomasjo/atom-latex#304]
Whenever I try to compile a tex file I get the error message below. Even though Atom throws the same error with #69 and #293, the underlying reason might be different. Therefore I am creating a new issue.  

```
Failed to activate the latex package
Cannot find module '/home/murat/.atom/packages/latex/lib/openers/'
```

Below, I am providing a detailed information.
```
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Ubuntu 14.04.5
**Thrown From**: [latex](https://github.com/thomasjo/atom-latex) package, v0.39.1


### Stack Trace

Failed to activate the latex package

```
At Cannot find module '/home/murat/.atom/packages/latex/lib/openers/'

Error: Cannot find module '/home/murat/.atom/packages/latex/lib/openers/'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at OpenerRegistry.initializeOpeners (/home/murat/.atom/packages/latex/lib/opener-registry.js:23:28)
    at new OpenerRegistry (/home/murat/.atom/packages/latex/lib/opener-registry.js:13:10)
    at new Latex (/home/murat/.atom/packages/latex/lib/latex.js:44:45)
    at Object.bootstrap (/home/murat/.atom/packages/latex/lib/main.js:65:20)
    at Object.activate (/home/murat/.atom/packages/latex/lib/main.js:8:10)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:183:20)
    at /usr/share/atom/resources/app.asar/src/package.js:795:25
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:20)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -6:41.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -6:38.9.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -6:36.5.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -6:36.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -6:36.1.0 latex:clean (atom-text-editor.editor)
  3x -6:20.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:46.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  6x -0:41.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:37.4.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:37.4.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:37.2.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:37.2.0 core:cancel (atom-text-editor.editor.is-focused)
  5x -0:13.5.0 latex:build (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "latex": {
    "alwaysOpenResultInAtom": true,
    "opener": "evince",
    "outputFormat": "dvi"
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.12.1
autocomplete-clang, v0.10.0
change-case, v0.6.3
file-icons, v1.7.25
highlight-selected, v0.11.2
language-latex, v1.0.0
language-matlab, v0.2.1
language-proto, v0.7.0
language-protobuf, v0.7.0
latex, v0.39.1
latexer, v0.3.0
linter, v1.11.18
linter-chktex, v1.3.0
linter-clang, v3.4.4
linter-matlab, v1.1.0
merge-conflicts, v1.4.4
minimap, v4.25.6
minimap-cursorline, v0.2.0
minimap-find-and-replace, v4.5.1
minimap-git-diff, v4.3.1
minimap-highlight-selected, v4.4.0
minimap-linter, v1.6.0
minimap-selection, v4.4.0
open-recent, v5.0.0
pdf-view, v0.53.0
project-manager, v3.3.3
wordcount, v2.8.0

# Dev
No dev packages
```

```

**Comment by yitzchak** [comment]
You can delete `alwaysOpenResultInAtom` from your configuration file. It's no longer used. Also, please upgrade to v0.40.0. Probably won't fix the issue, but just in cause. Finally, what OS are you on?

**Comment by yitzchak** [comment]
@eroniki One more issue, make sure you have at least Atom v1.10.0. There is a known issue with <v1.10.0 and the `path` library.

**Comment by eroniki** [comment]
Upgrading Atom version to v1.12.0 on Ubuntu allowed me to upgrade the atom-latex package (to v0.4 0.0) as well, which solved the problem right away.

**Comment by yitzchak** [comment]
Awesome. Glad it is working.
