### ISSUE TITLE
Uncaught ReferenceError: latex is not defined

### ISSUE THREAD

**Issue by PaulPichaureau** [thomasjo/atom-latex#330]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.9
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.2
**Thrown From**: [latex](https://github.com/thomasjo/atom-latex) package, v0.42.0

### Stack Trace

Uncaught ReferenceError: latex is not defined

```
At /Users/Paul/.atom/packages/latex/lib/process-manager.js:25

ReferenceError: latex is not defined
    at /Users/Paul/.atom/packages/latex/lib/process-manager.js:25:11
    at ChildProcess.exithandler (child_process.js:225:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
     -8:13.3.0 fuzzy-finder:toggle-buffer-finder (atom-text-editor.editor.is-focused)
     -8:11.8.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -8:11.8.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -7:58.9.0 latex:build (atom-text-editor.editor.is-focused)
     -7:45.5.0 fuzzy-finder:toggle-buffer-finder (atom-text-editor.editor.is-focused)
     -6:40.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -6:31.2.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -6:31.2.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  3x -6:29.6.0 latex:build (atom-text-editor.editor.is-focused)
     -6:17.3.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -6:09.9.0 core:save (atom-text-editor.editor.is-focused)
  7x -5:53.6.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
  5x -5:50 core:move-down (atom-text-editor.editor.is-focused)
 13x -5:48.4.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
  2x -5:42.3.0 latex:build (atom-text-editor.editor.is-focused)
     -0:00.6.0 editor:move-to-previous-subword-boundary (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "closeEmptyWindows": false,
    "disabledPackages": [
      "language-clojure",
      "language-csharp",
      "language-gfm",
      "language-go",
      "language-mustache",
      "language-objective-c",
      "language-sql",
      "language-toml",
      "metrics",
      "latex"
    ],
    "ignoredNames": [
      "*.aux",
      "*.log",
      "*.out",
      "*.aux",
      "*.out",
      "_*_.*",
      "*.fls",
      "*.fdb_latexmk",
      "*.pgf-plot.gnuplot",
      "#*.*#",
      "*.synctex",
      "*.gnuplot",
      "*.table",
      "*.snm",
      "*.nav",
      "*.toc"
    ],
    "telemetryConsent": "no"
  },
  "latex": {
    "enableExtendedBuildMode": false
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.16.5 (inactive)
file-bookmark, v1.0.2 (active)
language-latex, v1.0.0 (active)
language-markdown, v0.18.1 (active)
latex, v0.42.0 (inactive)
latextools, v0.8.5 (active)
markdown-folder, v0.5.0 (inactive)
pdf-view, v0.54.0 (active)
terminal-plus, v0.14.5 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (inactive)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (inactive)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (inactive)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (active)
language-go, v0.43.0 (inactive)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (inactive)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (inactive)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by yitzchak** [comment]
Thanks for reporting the issue!

In your list of packages `latex` is disabled and `latextools` is enabled. Did you change enable/disable some packages while the build was in process?

**Comment by PaulPichaureau** [comment]
Hi,

please delete this issue. I don't understand anything to atom or to this package yet :-)

I've just clicked on some window, but I really did'nt know what I was doing.

Sorry for the inconvenience.

**Comment by yitzchak** [comment]
@PaulPichaureau No worries. You *did* uncover package deactivation bug. The fix will be in the next version.
