### ISSUE TITLE
Uncaught TypeError: _viewsLogPanel2.default is not a constructor

### ISSUE THREAD

**Issue by nykh** [thomasjo/atom-latex#335]
[Enter steps to reproduce below:]

1. turn on LaTeX mode
2. run `core:close` (by `Ctrl+w`) or `core:cancel` (by `Esc`)

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Ubuntu 16.04.1
**Thrown From**: [latex](https://github.com/thomasjo/atom-latex) package, v0.42.2

### Stack Trace

Uncaught TypeError: _viewsLogPanel2.default is not a constructor

```
At /home/nykh/.atom/packages/latex/lib/loggers/default-logger.js:11

TypeError: _viewsLogPanel2.default is not a constructor
    at new DefaultLogger (/home/nykh/.atom/packages/latex/lib/loggers/default-logger.js:11:21)
    at Latex.getDefaultLogger (/home/nykh/.atom/packages/latex/lib/latex.js:57:12)
    at Latex.get (/home/nykh/.atom/packages/latex/lib/latex.js:18:56)
    at Object.hide (/home/nykh/.atom/packages/latex/lib/latex.js:90:9)
    at Object.handleHideLogPanel (/home/nykh/.atom/packages/latex/lib/main.js:49:17)
    at atom-workspace.coreCancel (/home/nykh/.atom/packages/latex/lib/main.js:19:33)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:259:29)
    at /opt/atom/resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/opt/atom/resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/opt/atom/resources/app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:16 fuzzy-finder:toggle-git-status-finder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:04.2.0 command-palette:toggle (input.hidden-input)
  3x -0:01.0 core:move-down (input.hidden-input)
     -0:00.4.0 editor:consolidate-selections (input.hidden-input)
     -0:00.4.0 core:cancel (input.hidden-input)
     -0:00.2.0 editor:consolidate-selections (input.hidden-input)
     -0:00.2.0 core:cancel (input.hidden-input)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-markdown",
      "pp-markdown",
      "linter-chktex"
    ],
    "projectHome": "/home/nykh/Documents",
    "telemetryConsent": "limited"
  },
  "latex": {
    "enableExtendedBuildMode": false
  }
}
```

### Installed Packages

```coffee
# User
aligner, v0.22.3 (active)
aligner-python, v1.0.1 (active)
api-docs, v0.0.6 (active)
autocomplete-paths, v1.0.5 (active)
autocomplete-python, v1.8.26 (active)
javascript-snippets, v1.2.1 (active)
language-cpp14, v0.6.2 (active)
language-dot, v1.6.0 (active)
language-latex, v1.0.0 (active)
language-matlab, v0.2.1 (active)
language-mediawiki, v2.2.0 (active)
language-scala, v1.1.8 (active)
latex, v0.42.2 (active)
linter, v1.11.21 (active)
linter-chktex, v1.3.0 (inactive)
linter-markdown, v3.0.2 (inactive)
merge-conflicts, v1.4.4 (active)
minimap, v4.26.6 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-git-diff, v4.3.1 (active)
minimap-highlight-selected, v4.5.0 (active)
pdf-view, v0.54.0 (active)
python-tools, v0.6.9 (active)
zentabs, v0.8.8 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (active)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

The package stopped working for this or that reason some versions ago. I feel I should finally try to report this so maybe at some point I can use it again.

**Comment by yitzchak** [comment]
Thanks for reporting the issue! We will look into it and see if we can reproduce the problem.
