### ISSUE TITLE
Unable to properly close Atom when using atom-latex

### ISSUE THREAD

**Issue by amyspark** [thomasjo/atom-latex#417]
Atom is unable to be closed properly when after using atom-latex. It ends up in a broken state:

![test](https://user-images.githubusercontent.com/13498015/30522747-b61a91d6-9bab-11e7-921d-7e48b50bf50a.jpg)

Atom version: 1.21.0-beta.0 (Windows x64)
atom-latex version: 0.47.0

```
C:\Users\Amalia\.atom\packages\latex\lib\main.js:95 Uncaught (in promise) ReferenceError: latex is not defined
    at Disposable.disposalAction (file:///C:/Users/Amalia/.atom/packages/latex/lib/main.js:65:11)
    at Disposable.module.exports.Disposable.dispose (C:\Users\Amalia\AppData\Local\atom\app-1.21.0-beta0\resources\app\node_modules\event-kit\lib\disposable.js:24:22)
    at C:\Users\Amalia\AppData\Local\atom\app-1.21.0-beta0\resources\app\node_modules\service-hub\node_modules\event-kit\lib\composite-disposable.js:25:35
    at Set.forEach (native)
    at CompositeDisposable.module.exports.CompositeDisposable.dispose (C:\Users\Amalia\AppData\Local\atom\app-1.21.0-beta0\resources\app\node_modules\service-hub\node_modules\event-kit\lib\composite-disposable.js:24:32)
    at Provider.module.exports.Provider.destroy (C:\Users\Amalia\AppData\Local\atom\app-1.21.0-beta0\resources\app\node_modules\service-hub\lib\provider.js:45:45)
    at Disposable.disposalAction (C:\Users\Amalia\AppData\Local\atom\app-1.21.0-beta0\resources\app\node_modules\service-hub\lib\service-hub.js:36:26)
    at Disposable.module.exports.Disposable.dispose (C:\Users\Amalia\AppData\Local\atom\app-1.21.0-beta0\resources\app\node_modules\service-hub\node_modules\event-kit\lib\disposable.js:26:22)
    at C:\Users\Amalia\AppData\Local\atom\app-1.21.0-beta0\resources\app\node_modules\event-kit\lib\composite-disposable.js:27:35
    at Set.forEach (native)
    at CompositeDisposable.module.exports.CompositeDisposable.dispose (C:\Users\Amalia\AppData\Local\atom\app-1.21.0-beta0\resources\app\node_modules\event-kit\lib\composite-disposable.js:26:32)
    at Package.module.exports.Package.deactivateResources (C:\Users\Amalia\AppData\Local\atom\app-1.21.0-beta0\resources\app\src\package.js:860:20)
    at Package.module.exports.Package.deactivate (C:\Users\Amalia\AppData\Local\atom\app-1.21.0-beta0\resources\app\src\package.js:804:18)
    at PackageManager.deactivatePackage (C:\Users\Amalia\AppData\Local\atom\app-1.21.0-beta0\resources\app\src\package-manager.js:771:43)
    at Promise.all.getLoadedPackages.map.pack (C:\Users\Amalia\AppData\Local\atom\app-1.21.0-beta0\resources\app\src\package-manager.js:754:67)
    at Array.map (native)
    at config.transactAsync (C:\Users\Amalia\AppData\Local\atom\app-1.21.0-beta0\resources\app\src\package-manager.js:754:50)
    at Config.module.exports.Config.transactAsync (C:\Users\Amalia\AppData\Local\atom\app-1.21.0-beta0\resources\app\src\config.js:346:24)
    at PackageManager.deactivatePackages (C:\Users\Amalia\AppData\Local\atom\app-1.21.0-beta0\resources\app\src\package-manager.js:753:29)
    at C:\Users\Amalia\AppData\Local\atom\app-1.21.0-beta0\resources\app\src\atom-environment.js:811:47
```

**Comment by yitzchak** [comment]
Thanks for reporting the issue! We will look into it and try to reproduce the problem.

**Comment by yitzchak** [comment]
I have reproduced this bug and have a fix in the works.
