### ISSUE TITLE
Use custom TEXINPUTS path and/or latexmkrc

### ISSUE THREAD

**Issue by andrewrynhard** [thomasjo/atom-latex#43]
It would be nice to support custom paths for inclusion. For example if a user has custom classes or packages shared amongst many documents, the environment variable TEXINPUTS can be set pointing to a directory holding these files (the directory is searched recursively so subdirectories need not be included). I haven't used it yet but there is also latexmkrc. The documentation on it starts on pg. 12 (CONFIGURATION/INITIALIZATION (RC) FILES) in the pdf: http://users.phys.psu.edu/~collins/latexmk/latexmk-439.pdf

**Comment by arynhard** [comment]
Trying the latexmkrc option I receive the following error:

```
TypeError: old path must be a string
  at TypeError (native)
  at Object.fs.renameSync (fs.js:580:18)
  at Object.fsPlus.moveSync (/Applications/Atom.app/Contents/Resources/app/node_modules/fs-plus/lib/fs-plus.js:221:17)
  at Object.module.exports.moveResult (/Users/user/.atom/packages/latex/lib/latex.coffee:96:8)
  at /Users/user/.atom/packages/latex/lib/latex.coffee:39:12
  at /Users/user/.atom/packages/latex/lib/builders/latexmk.coffee:19:9
  at ChildProcess.exithandler (child_process.js:736:7)
  at ChildProcess.emit (events.js:110:17)
  at maybeClose (child_process.js:1009:16)
  at Socket.<anonymous> (child_process.js:1177:11)
  at Socket.emit (events.js:107:17)
  at Pipe.close (net.js:469:12)
```
