### ISSUE TITLE
Uncaught TypeError: Cannot read property 'filePath' of undefined

### ISSUE THREAD

**Issue by arynhard** [thomasjo/atom-latex#45]
This happens randomly but often enough to file an issue. Still looking for a way to reproduce this, but opening this issue for now.

**Atom Version**: 0.174.0
**System**: Mac OS X 10.10.1
**Thrown From**: [latex](https://github.com/thomasjo/atom-latex) package, v0.15.2

### Stack Trace

Uncaught TypeError: Cannot read property 'filePath' of undefined

```
At /Users/user/Development/projects/dotfiles/atom/packages/latex/lib/latex.coffee:115

TypeError: Cannot read property 'filePath' of undefined
  at Object.module.exports.showResult (/Users/user/Development/projects/dotfiles/atom/packages/latex/lib/latex.coffee:115:8)
  at /Users/user/Development/projects/dotfiles/atom/packages/latex/lib/latex.coffee:40:12
  at /Users/user/Development/projects/dotfiles/atom/packages/latex/lib/builders/latexmk.coffee:19:9
  at ChildProcess.exithandler (child_process.js:736:7)
  at ChildProcess.emit (events.js:110:17)
  at maybeClose (child_process.js:1009:16)
  at Socket.<anonymous> (child_process.js:1177:11)
  at Socket.emit (events.js:107:17)
  at Pipe.close (net.js:469:12)

```

### Commands

```
     -1:09.5 core:move-right (atom-text-editor.editor)
  2x -1:09.2 editor:newline (atom-text-editor.editor)
     -1:07.6 core:backspace (atom-text-editor.editor)
  2x -1:06.9 core:save (atom-text-editor.editor)
     -0:13.2 core:copy (atom-text-editor.editor)
     -0:12.9 core:move-right (atom-text-editor.editor)
     -0:12.7 editor:newline (atom-text-editor.editor)
     -0:12.5 core:paste (atom-text-editor.editor)
     -0:12.1 core:move-left (atom-text-editor.editor)
     -0:11.7 core:backspace (atom-text-editor.editor)
     -0:11.0 core:save (atom-text-editor.editor)
     -0:08.5 pane:show-next-item (atom-text-editor.editor)
     -0:07.4 core:save (atom-text-editor.editor)
     -0:01.5 pane:show-previous-item (atom-text-editor.editor)
     -0:00.6 latex:build (atom-text-editor.editor)
     -0:00.0 pane:show-next-item (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "seti-syntax"
    ]
  },
  "latex": {
    "outputDirectory": "./.auxdir",
    "engine": "xelatex"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v1.1.0
autocomplete-snippets, v0.3.2
language-docker, v1.1.2
language-latex, v0.4.1
latex, v0.15.2
pdf-view, v0.14.0
script, v2.16.0
seti-syntax, v0.2.1

# Dev
No dev packages
```

/cc @atom/core

**Comment by thomasjo** [comment]
I believe this is caused by the same bug discovered by @nscaife in #46, so possibly a duplicate, but will leave it open until I can confirm.

**Comment by thomasjo** [comment]
I just published a new version that should resolve this issue. Please reopen if the problem persists.

**Comment by Victorystick** [comment]
**Atom**: 0.176.0
**OS**: Ubuntu 14.04 LTS

I get this as soon as I try to build since the update.

```
TypeError: Cannot read property 'filePath' of undefined
  at Object.module.exports.showResult (/home/eoskseg/.atom/packages/latex/lib/latex.coffee:161:15)
  at /home/eoskseg/.atom/packages/latex/lib/latex.coffee:54:45
  at /home/eoskseg/.atom/packages/latex/lib/builders/latexmk.coffee:19:9
  at ChildProcess.exithandler (child_process.js:736:7)
  at ChildProcess.emit (events.js:110:17)
  at maybeClose (child_process.js:1009:16)
  at Socket.<anonymous> (child_process.js:1177:11)
  at Socket.emit (events.js:107:17)
  at Pipe.close (net.js:469:12)
```
