### ISSUE TITLE
Failed to activate

### ISSUE THREAD

**Issue by delta-one** [thomasjo/atom-latex#492]
When I start Atom 1.32, I still get a "Failed to activate" message. I tried deactivating all non-core packages, but still the same result.

**Atom**: 1.32.0 x64
**Electron**: 2.0.9
**OS**: Debian GNU/Linux
**Thrown From**: [latex](https://github.com/thomasjo/atom-latex) package 0.50.0

### Stack Trace

Failed to activate the latex package

```
At Cannot find module '../type/js/undefined'

Error: Cannot find module '../type/js/undefined'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/static/<embedded>:11:154364)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:145671)
    at /packages/latex/node_modules/js-yaml/lib/js-yaml/schema/default_full.js:21:5)
    at /packages/latex/node_modules/js-yaml/lib/js-yaml/schema/default_full.js:27:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:146381)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:149928)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:145671)
    at /packages/latex/node_modules/js-yaml/lib/js-yaml/loader.js:9:27)
    at /packages/latex/node_modules/js-yaml/lib/js-yaml/loader.js:1600:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:146381)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:149928)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:145671)
    at /packages/latex/node_modules/js-yaml/lib/js-yaml.js:4:14)
    at /packages/latex/node_modules/js-yaml/lib/js-yaml.js:41:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:146381)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:149928)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
```

**Comment by thomasjo** [comment]
I'm unable to reproduce this problem. Looks like something might have gone wrong during installation.
Can you please try re-installing the package (first uninstall, then install) to see if that resolves the problem?
