### ISSUE TITLE
Failed to activate the latex package  ``` At OpenerImpl is not a constructor

### ISSUE THREAD

**Issue by MONTYYUAN** [thomasjo/atom-latex#495]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.1 x64
**Electron**: 2.0.9
**OS**: Unknown Windows version
**Thrown From**: [latex](https://github.com/thomasjo/atom-latex) package 0.50.0

### Stack Trace

Failed to activate the latex package

```
At OpenerImpl is not a constructor

TypeError: OpenerImpl is not a constructor
    at OpenerRegistry.initializeOpeners (/packages/latex/lib/opener-registry.js:24:24)
    at /packages/latex/lib/opener-registry.js:13:10)
    at /packages/latex/lib/latex.js:27:45)
    at Object.bootstrap (/packages/latex/lib/main.js:85:20)
    at Object.activate (/packages/latex/lib/main.js:7:10)
    at Package.activateNow (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:3032531)
    at string.e.trim.length.activationHookSubscriptions.add.packageManager.onDidTriggerActivationHook (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:14:2445)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:1186953)
    at Emitter.emit (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:1188394)
    at PackageManager.triggerDeferredActivationHooks (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:380394)
    at Promise.all.then (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:379192)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
language-latex 1.2.0 
latex 0.50.0 
latex-completions 0.3.5 
pdf-view 0.71.0 
simplified-chinese-menu 5.3.5 
```

**Comment by MONTYYUAN** [comment]
need help

**Comment by thomasjo** [comment]
@MONTYYUAN Have you tried re-installing the package? Uninstall first, then install it again. I'm unable to reproduce the problem, so I'm thinking something might have gone wrong when you first installed the package.

**Comment by MONTYYUAN** [comment]
@thomasjo Yes, I have reinstalled Atom, and reinstalled latex package,  try a lot, but it doesn't work. i don't know what's "OpenerImpl is not a constructorl" mean. Then I install texstudio, this software is fine to use latex…

**Comment by thomasjo** [comment]
@madeindjs Your issue is different. If you update Atom to 1.32 stable release, the problem will go away. There was a regression introduced in Atom 1.32 beta that was fixed before it was released to stable.

I'm currently unable to reproduce the issue reported by @MONTYYUAN, which means it's not possible for me to fix it since I have no clue what might be wrong.

**Comment by SevenSymmetry** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.38.2 x64
**Electron**: 2.0.18
**OS**: Unknown Windows version
**Thrown From**: [latex](https://github.com/thomasjo/atom-latex) package 0.50.2


### Stack Trace

Failed to activate the latex package

```
At Cannot find module 'lodash'

Error: Cannot find module 'lodash'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.38.2/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:155156)
    at Module.require (/app.asar/static/index.js:53:43)
    at require (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:146462)
    at /packages/atom-latex-master/lib/composer.js:19:15)
    at /packages/atom-latex-master/lib/composer.js:15:30)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:147172)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:60:45)
    at require (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:146462)
    at /packages/atom-latex-master/lib/latex.js:15:17)
    at /packages/atom-latex-master/lib/latex.js:18:27)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:147172)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:60:45)
    at require (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:146462)
    at Object.bootstrap (/packages/atom-latex-master/lib/main.js:84:19)
    at Object.activate (/packages/atom-latex-master/lib/main.js:7:10)
    at Package.activateNow (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:3539161)
    at string.e.trim.length.activationHookSubscriptions.add.packageManager.onDidTriggerActivationHook (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:14:2445)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:1206583)
    at Emitter.emit (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:1208024)
    at PackageManager.triggerActivationHook (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:381860)
```

### Commands

```
```

### Non-Core Packages

```
latex 0.50.2 
language-latex 1.2.0 
pdf-view 0.71.0 
```
