### ISSUE TITLE
Uncaught TypeError: Cannot read property 'open' of undefined

### ISSUE THREAD

**Issue by despairblue** [thomasjo/atom-latex#53]
1. use the sync option

**Atom Version**: 0.177.0
**System**: linux 3.14.26-1-lts
**Thrown From**: [latex](https://github.com/thomasjo/atom-latex) package, v0.18.0

### Stack Trace

Uncaught TypeError: Cannot read property 'open' of undefined

```
At /home/despairblue/.atom/packages/latex/lib/latex.coffee:104

TypeError: Cannot read property 'open' of undefined
  at Object.module.exports.sync (/home/despairblue/.atom/packages/latex/lib/latex.coffee:104:11)
  at atom-workspace.<anonymous> (/home/despairblue/.atom/packages/latex/lib/latex.coffee:16:59)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app/node_modules/command-palette/lib/command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/home/despairblue/.atom/packages/bug-report/node_modules/atom-space-pen-views/lib/select-list-view.js:335:21)
  at space-pen-div.atom.commands.add.core:confirm (/home/despairblue/.atom/packages/bug-report/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app/src/window-event-handler.js:170:20)

```

### Commands

```
     -0:34.5 editor:move-to-end-of-screen-line (atom-text-editor.editor.autocomplete-active.is-focused)
     -0:34.1 core:move-left (atom-text-editor.editor.autocomplete-active.is-focused)
     -0:33.9 core:paste (atom-text-editor.editor.autocomplete-active.is-focused)
  5x -0:33.3 editor:move-to-beginning-of-word (atom-text-editor.editor.autocomplete-active.is-focused)
     -0:32.3 core:move-right (atom-text-editor.editor.autocomplete-active.is-focused)
  6x -0:31.7 editor:select-to-beginning-of-word (atom-text-editor.editor.autocomplete-active.is-focused)
     -0:30.4 core:select-up (atom-text-editor.editor.autocomplete-active.is-focused)
     -0:29.8 core:select-down (atom-text-editor.editor.autocomplete-active.is-focused)
  2x -0:29.3 core:backspace (atom-text-editor.editor.autocomplete-active.is-focused)
     -0:11.4 core:save (atom-text-editor.editor.autocomplete-active.is-focused)
     -0:07.0 command-palette:toggle (atom-text-editor.editor.autocomplete-active.is-focused)
     -0:05.5 core:confirm (atom-text-editor.editor.mini)
     -0:05.4 latex:build (atom-text-editor.editor.autocomplete-active.is-focused)
     -0:03.7 command-palette:toggle (atom-text-editor.editor.autocomplete-active.is-focused)
     -0:01.8 core:confirm (atom-text-editor.editor.mini)
     -0:01.8 latex:sync (atom-text-editor.editor.autocomplete-active.is-focused)
```

### Config

```json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "welcome",
      "metrics",
      "autocomplete",
      "incremental-search",
      "Tern",
      "grunt-runner",
      "tree-view-open-files",
      "tree-view-breadcrumb",
      "atomatigit"
    ],
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ],
    "projectHome": "/home/despairblue/vcs/git/",
    "destroyEmptyPanes": false,
    "autoHideMenuBar": true
  },
  "latex": {}
}
```

### Installed Packages

```coffee
# User
angularjs, v0.1.0
atom-beautify, v0.21.2
atom-color-highlight, v3.0.6
atom-jasmine, v0.5.0
atom-ternjs, v0.4.13
autocomplete-paths, v1.0.2
autocomplete-plus, v2.1.3
autocomplete-snippets, v1.0.1
block-travel, v0.10.0
bug-report, v0.5.5
color-picker, v1.4.4
compare-files, v0.4.0
docblockr, v0.5.8
editorconfig, v0.3.0
file-icons, v1.4.8
git-log, v0.2.0
go-plus, v3.2.1
grammar-token-limit, v0.1.1
highlight-selected, v0.7.0
indentation-indicator, v0.4.1
javascript-snippets, v1.0.0
keybinding-cheatsheet, v0.0.7
language-dockerfile, v0.1.0
language-haskell, v1.0.0
language-latex, v0.4.1
language-nimrod, v0.1.0
language-puppet, v0.10.0
language-tss, v0.0.1
latex, v0.18.0
linter, v0.11.1
linter-coffeelint, v0.1.7
linter-eslint, v0.3.1
linter-jshint, v0.1.0
linter-puppet-lint, v0.2.3
minimap, v4.1.2
minimap-color-highlight, v4.0.0
minimap-find-and-replace, v3.1.0
minimap-git-diff, v3.1.1
minimap-highlight-selected, v4.0.0
open-last-project, v0.2.2
package-cop, v0.2.2
project-manager, v1.15.5
regex-railroad-diagram, v0.6.3
tab-smart-sort, v0.1.2
tabs-to-spaces, v0.8.1
test-status, v0.27.1
zentabs, v0.6.1

# Dev
autocomplete-plus, v2.0.2
```

/cc @atom/core

**Comment by thomasjo** [comment]
Thanks for reporting this; fixed in v0.18.1.

---
As a side note, your problem was caused by missing support for a "native" `Opener` implementation for GNU/Linux distributions. As of right now, you should install the [PDF View package](https://atom.io/packages/pdf-view) to get partial functionality as far as automatically opening/syncing documents.
