### ISSUE TITLE
Uncaught Error: Cannot find module './progress-indicator-view'

### ISSUE THREAD

**Issue by thedataking** [thomasjo/atom-latex#73]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.189.0
**System**: Mac OS X 10.10.3
**Thrown From**: [latex](https://github.com/thomasjo/atom-latex) package, v0.21.0

### Stack Trace

Uncaught Error: Cannot find module './progress-indicator-view'

```
At module.js:330

Error: Cannot find module './progress-indicator-view'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Composer.module.exports.Composer.showProgressIndicator (/Users/perl/.atom/packages/latex/lib/composer.coffee:6:3)
  at Composer.module.exports.Composer.build (/Users/perl/.atom/packages/latex/lib/composer.coffee:24:5)
  at atom-workspace.<anonymous> (/Users/perl/.atom/packages/latex/lib/main.coffee:8:8)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:242:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:552:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:392:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:180:20)

```

### Commands

```
     -0:43.9 settings-view:open (atom-text-editor.editor.is-focused)
  2x -0:14.3 latex:build (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".DS_Store",
      ".bbl",
      ".aux",
      ".blg",
      ".fls",
      ".log"
    ],
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ],
    "projectHome": "/Users/perl/Dropbox/Work/papers-and-presentations",
    "disabledPackages": [
      "open-last-project"
    ]
  },
  "latex": {
    "texPath": "/opt/local/bin"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-bibtex, v0.5.6
autocomplete-plus, vundefined
block-travel, v1.0.2
editor-stats, v0.17.0
file-icons, v1.5.2
language-haskell, v1.0.0
language-latex, v0.4.1
latex, v0.21.0
linter, v0.12.0
linter-coffeelint, v0.2.1
linter-csslint, v0.0.11
linter-javac, v0.1.3
linter-jshint, v0.1.0
linter-pylint, v0.2.1
linter-xmllint, v0.0.5
symbols-tree-view, v0.8.3
wordcount, v2.2.0

# Dev
No dev packages
```

**Comment by thomasjo** [comment]
This is most likely caused by a lingering bug in Atom related to module caching. Restarting Atom should resolve the issue. Please let us know if that fixed the problem.

**Comment by thedataking** [comment]
Yes. Restarting Atom fixed the problem. Thanks for the quick response and all your hard work on this module. I use LaTeX to write papers almost every day and appreciate the steady flow of improvements.

**Comment by thomasjo** [comment]
For those whom are interested the issue is caused by, as stated earlier, the module cache (aka require cache) in Node.js/io.js; when Atom updates packages, the previous version of a package's main module remains in the cache. This causes all kinds of problems. In this specific case I had relocated the views to a separate `views/` directory, so attempt to load the progress indicator failed since the view no longer existed in the old location.

**Comment by thomasjo** [comment]
> Thanks for the quick response and all your hard work on this module. I use LaTeX to write papers almost every day and appreciate the steady flow of improvements.

Thanks for the kind words. I wish I had more free time to crank out more features quicker though.
