### ISSUE TITLE
Uncaught TypeError: Cannot read property 'editor' of undefined

### ISSUE THREAD

**Issue by nscaife** [thomasjo/atom-latex#74]
1. Search project for arbitrary string.
2. Accidentally hit build hotkey while still on Project Find Results tab in Atom.
3. Facepalm.

**Atom Version**: 0.192.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [latex](https://github.com/thomasjo/atom-latex) package, v0.21.0

### Stack Trace

Uncaught TypeError: Cannot read property 'editor' of undefined

```
At C:\Users\Nolen\.atom\packages\latex\lib\composer.coffee:11

TypeError: Cannot read property 'editor' of undefined
  at Composer.module.exports.Composer.build (C:\Users\Nolen\.atom\packages\latex\lib\composer.coffee:11:6)
  at atom-workspace.commands.atom.commands.add.latex:build (C:\Users\Nolen\.atom\packages\latex\lib\main.coffee:10:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (c:\Users\Nolen\AppData\Local\atom\app-0.192.0\resources\app\src\command-registry.js:238:29)
  at CommandRegistry.handleCommandEvent (c:\Users\Nolen\AppData\Local\atom\app-0.192.0\resources\app\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (c:\Users\Nolen\AppData\Local\atom\app-0.192.0\resources\app\src\command-registry.js:153:19)
  at EventEmitter.<anonymous> (c:\Users\Nolen\AppData\Local\atom\app-0.192.0\resources\app\src\window-event-handler.js:73:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -0:59.0 find-and-replace:show (atom-text-editor.editor)
     -0:56.9 editor:move-to-first-character-of-line (atom-text-editor.editor.mini)
     -0:54.2 project-find:show (atom-text-editor.editor.mini)
  3x -0:52.9 core:backspace (atom-text-editor.editor.mini)
     -0:51.4 core:confirm (atom-text-editor.editor.mini)
     -0:04.5 latex:build (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  },
  "latex": {}
}
```

### Installed Packages

```coffee
# User
atom-pair, v1.1.5
column-select, v0.2.0
file-icons, v1.5.4
git-tab-status, v1.7.0
language-latex, v0.6.1
language-yara, v3.1.1
latex, v0.21.0
linter, v0.12.0
linter-chktex, v0.1.2
linter-coffeelint, v0.2.1
linter-write-good, v0.4.2
monokai, v0.14.0
symbols-tree-view, v0.9.2
wordcount, v2.2.2

# Dev
linter-chktex, v0.1.2
```

**Comment by thomasjo** [comment]
Thanks for the report. Should be fixed in newest release (v0.22.0).
